web: &web
  build: .
  links:
   - db
   - redis
  ports:
   - "5000:5000"
  environment:
    TOSHI_ENV: production
  command: bundle exec puma
blockworker:
  <<: *web
  command: bundle exec sidekiq -q blocks -c 1 -r ./config/environment.rb
  ports: []
transactionworker:
  <<: *web
  command: bundle exec sidekiq -q transactions -c 1 -r ./config/environment.rb
  ports: []
peermanager:
  <<: *web
  ports: []
  command: bundle exec ruby bin/peer_manager.rb
db:
  image: "postgres:9.6"
redis:
  image: "redis:2.8"
  
