source 'https://rubygems.org'

gem 'bundler','1.15.4'
gem 'rake'
gem 'foreman'
#gem 'bitcoin-ruby', github: 'lian/bitcoin-ruby', require: 'bitcoin', ref: '69123208d45a19da446c5e0079d4fa2e225e5be6'
#gem 'bitcoin-ruby', github: 'lian/bitcoin-ruby', require: 'bitcoin', ref: '443157f9d96e94de05244d5b27abfc32e67cbba4'
gem 'bitcoin-ruby', github: 'astrolite/bitcoin-ruby', require: 'bitcoin', branch: 'master'
gem 'ffi'
gem 'eventmachine'
gem 'pg'
gem 'sequel'
gem 'sidekiq'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib'
gem 'puma'
gem 'faye-websocket'
gem 'bugsnag-em'
gem 'scrypt'
gem 'newrelic_rpm'
gem 'builder'

group :test do
  gem 'rspec'
  gem 'rack-test', :require => 'rack/test'
  gem 'database_cleaner'
end
